### ISSUE TITLE
ModuleNotFoundError: No module named 'mingus.extra.LilyPond'

### ISSUE THREAD

**Issue by abstractdonut** [bspaans/python-mingus#75]
I can't import the LilyPond module for mingus in python3.

```
>>> import mingus.extra.LilyPond
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mingus.extra.LilyPond'
```
I have mingus properly installed from source, and LilyPond installed from apt as well.

**Comment by Joeytje50** [comment]
How did you manage to resolve this issue? I can't find any instructions anywhere else on the internet.

Edit: I was able to find https://www.georgefane.com/all-posts/generating-sheet-music-with-python-lilypond-and-mingus which made me think that mingus' instructions were incorrect. The solution is to `import mingus.extra.lilypond` instead of importing lilypond with uppercase L and P.
